services:
  ppocr:
    image: paddlepaddle/paddle:2.6.2-gpu-cuda11.2-cudnn8.2-trt8.0
    container_name: ppocr
    ipc: host
    network_mode: "bridge"
    stdin_open: true
    tty: true
    volumes:
      - .:/paddle_custom
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
